I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 119, in script call
    $ batalha.battle()
  File "game/script.rpy", line 119, in script call
    $ batalha.battle()
ScriptError: could not find label 'manobras'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "E:\Downloads 2\renpy-8.0.0-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "E:\Downloads 2\renpy-8.0.0-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "E:\Downloads 2\renpy-8.0.0-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "E:\Downloads 2\renpy-8.0.0-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "game/script.rpy", line 119, in script call
    $ batalha.battle()
  File "game/script.rpy", line 119, in script call
    $ batalha.battle()
  File "E:\Downloads 2\renpy-8.0.0-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'manobras'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Tuto 1.0
Sun Jan 29 00:04:49 2023
